resource "local_file" "ws" {
  count = 500


  content  = <<EOF
#
# Autogenerated by Terraform
# https://github.com/hashi-strawb/tfc-monorepo-test/blob/main/repo_dirs/main.tf
#

module "pet" {
  source = "../../modules/random"
}
EOF
  filename = "../individual-workspaces/ws-${format("%04d", count.index)}/main.tf"
}
